package insanebikesteam.insanebikes;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ActivateUserHandler implements java.io.Serializable, WorkItemHandler {

    static final long serialVersionUID = 1L;
    static final int DEFAULT_CREDIT = 50;

    public ActivateUserHandler() {
    }

    public void	abortWorkItem(WorkItem workItem, WorkItemManager manager) {}

    public void	executeWorkItem(WorkItem workItem, WorkItemManager manager) {
        
        User user = (User) workItem.getParameter("User");
        user.setActive(true);
        user.setCredit(DEFAULT_CREDIT);
        
        Map<String,Object> results = new HashMap<String,Object>();
        results.put("UpdatedUser", user);
        
        manager.completeWorkItem(workItem.getId(), results);
    }
}
