package insanebikesteam.insanebikes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@org.kie.api.definition.type.Description("Data object of the bike.")
@org.kie.api.definition.type.Label("Bike")
public class Bike implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BIKE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "BIKE_ID_GENERATOR", sequenceName = "BIKE_ID_SEQ")
   @org.kie.api.definition.type.Description("Auto generated bike ID.")
   @org.kie.api.definition.type.Label("Bike Id")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Type")
   @org.kie.api.definition.type.Description("Type of the bike.")
   private java.lang.String type;

   @org.kie.api.definition.type.Label("Color")
   @org.kie.api.definition.type.Description("Color of the bike.")
   private java.lang.String color;

   @org.kie.api.definition.type.Label("Location")
   @org.kie.api.definition.type.Description("GPS coordinates of the bike.")
   private java.lang.String location;

   @org.kie.api.definition.type.Label("Available")
   @org.kie.api.definition.type.Description("Detection of bike availability.")
   private boolean available;

   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Description("History of notes of the bike (e.g. if the bike was damaged, repaired, etc...).")
   @org.kie.api.definition.type.Label("Notes")
   private java.util.List<java.lang.String> notes;

   @org.kie.api.definition.type.Label("Lock Code")
   private java.lang.String lockCode;

   @org.kie.api.definition.type.Label(value = "Firebase ID")
   private java.lang.String fbid;

   public Bike()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getColor()
   {
      return this.color;
   }

   public void setColor(java.lang.String color)
   {
      this.color = color;
   }

   public java.lang.String getLocation()
   {
      return this.location;
   }

   public void setLocation(java.lang.String location)
   {
      this.location = location;
   }

   public boolean isAvailable()
   {
      return this.available;
   }

   public void setAvailable(boolean available)
   {
      this.available = available;
   }

   public java.util.List<java.lang.String> getNotes()
   {
      return this.notes;
   }

   public void setNotes(java.util.List<java.lang.String> notes)
   {
      this.notes = notes;
   }

   public java.lang.String getLockCode()
   {
      return this.lockCode;
   }

   public void setLockCode(java.lang.String lockCode)
   {
      this.lockCode = lockCode;
   }

   public java.lang.String getFbid()
   {
      return this.fbid;
   }

   public void setFbid(java.lang.String fbid)
   {
      this.fbid = fbid;
   }

   public Bike(java.lang.Long id, java.lang.String type, java.lang.String color,
         java.lang.String location, boolean available,
         java.util.List<java.lang.String> notes, java.lang.String lockCode,
         java.lang.String fbid)
   {
      this.id = id;
      this.type = type;
      this.color = color;
      this.location = location;
      this.available = available;
      this.notes = notes;
      this.lockCode = lockCode;
      this.fbid = fbid;
   }

}