package insanebikesteam.insanebikes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@org.kie.api.definition.type.Label("Bike Stand")
@org.kie.api.definition.type.Description("Data object of the Bike Stand.")
public class BikeStand implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BIKESTAND_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "BIKESTAND_ID_GENERATOR", sequenceName = "BIKESTAND_ID_SEQ")
   @org.kie.api.definition.type.Label("Bike Stand Id")
   @org.kie.api.definition.type.Description("Auto generated bike stand ID.")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Location")
   @org.kie.api.definition.type.Description("GPS coordinates of the bike stand location.")
   private java.lang.String location;

   @org.kie.api.definition.type.Label("Capacity")
   @org.kie.api.definition.type.Description("Maximum capacity of the bike stand.")
   private int capacity;

   @org.kie.api.definition.type.Label("Bikes in Stand")
   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Description("List of bike that are docked in the bike stand at the moment.")
   private java.util.List<insanebikesteam.insanebikes.Bike> bikes_in_stand;

   @org.kie.api.definition.type.Label(value = "Firebase ID")
   private java.lang.String fbid;

   public BikeStand()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getLocation()
   {
      return this.location;
   }

   public void setLocation(java.lang.String location)
   {
      this.location = location;
   }

   public int getCapacity()
   {
      return this.capacity;
   }

   public void setCapacity(int capacity)
   {
      this.capacity = capacity;
   }

   public java.util.List<insanebikesteam.insanebikes.Bike> getBikes_in_stand()
   {
      return this.bikes_in_stand;
   }

   public void setBikes_in_stand(
         java.util.List<insanebikesteam.insanebikes.Bike> bikes_in_stand)
   {
      this.bikes_in_stand = bikes_in_stand;
   }

   public java.lang.String getFbid()
   {
      return this.fbid;
   }

   public void setFbid(java.lang.String fbid)
   {
      this.fbid = fbid;
   }

   public BikeStand(java.lang.Long id, java.lang.String location, int capacity,
         java.util.List<insanebikesteam.insanebikes.Bike> bikes_in_stand,
         java.lang.String fbid)
   {
      this.id = id;
      this.location = location;
      this.capacity = capacity;
      this.bikes_in_stand = bikes_in_stand;
      this.fbid = fbid;
   }

}