package insanebikesteam.insanebikes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@org.kie.api.definition.type.Description("Data object of the bike rental.")
@org.kie.api.definition.type.Label("Bike Rental")
public class BikeRental implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "BIKERENTAL_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "BIKERENTAL_ID_GENERATOR", sequenceName = "BIKERENTAL_ID_SEQ")
   @org.kie.api.definition.type.Label("Rental id")
   @org.kie.api.definition.type.Description("Unique, auto generated id of bike rental.")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("User")
   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Description("User that rented the bike.")
   private insanebikesteam.insanebikes.User user;

   @org.kie.api.definition.type.Label("Bike")
   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Description("Bike that has been rented.")
   private insanebikesteam.insanebikes.Bike bike;

   @org.kie.api.definition.type.Label("Start Time")
   @org.kie.api.definition.type.Description("Start time of rental.")
   private java.util.Date start_time;

   @org.kie.api.definition.type.Label("End Time")
   @org.kie.api.definition.type.Description("End time of rental")
   private java.util.Date end_time;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Description("Bike stand from the bike has been rented.")
   @org.kie.api.definition.type.Label("Start Point")
   private insanebikesteam.insanebikes.BikeStand start_point;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Description("Bike stand where the bike has been returned.")
   @org.kie.api.definition.type.Label("End Point")
   private insanebikesteam.insanebikes.BikeStand end_point;

   public BikeRental()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public insanebikesteam.insanebikes.User getUser()
   {
      return this.user;
   }

   public void setUser(insanebikesteam.insanebikes.User user)
   {
      this.user = user;
   }

   public insanebikesteam.insanebikes.Bike getBike()
   {
      return this.bike;
   }

   public void setBike(insanebikesteam.insanebikes.Bike bike)
   {
      this.bike = bike;
   }

   public java.util.Date getStart_time()
   {
      return this.start_time;
   }

   public void setStart_time(java.util.Date start_time)
   {
      this.start_time = start_time;
   }

   public java.util.Date getEnd_time()
   {
      return this.end_time;
   }

   public void setEnd_time(java.util.Date end_time)
   {
      this.end_time = end_time;
   }

   public insanebikesteam.insanebikes.BikeStand getStart_point()
   {
      return this.start_point;
   }

   public void setStart_point(insanebikesteam.insanebikes.BikeStand start_point)
   {
      this.start_point = start_point;
   }

   public insanebikesteam.insanebikes.BikeStand getEnd_point()
   {
      return this.end_point;
   }

   public void setEnd_point(insanebikesteam.insanebikes.BikeStand end_point)
   {
      this.end_point = end_point;
   }

   public BikeRental(java.lang.Long id, insanebikesteam.insanebikes.User user,
         insanebikesteam.insanebikes.Bike bike, java.util.Date start_time,
         java.util.Date end_time,
         insanebikesteam.insanebikes.BikeStand start_point,
         insanebikesteam.insanebikes.BikeStand end_point)
   {
      this.id = id;
      this.user = user;
      this.bike = bike;
      this.start_time = start_time;
      this.end_time = end_time;
      this.start_point = start_point;
      this.end_point = end_point;
   }

}