package insanebikesteam.insanebikes;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculatePriceHandler implements java.io.Serializable, WorkItemHandler {

    static final long serialVersionUID = 1L;
    
    static final int PIN_MIN_VALUE_1 = 1;
    static final int PIN_MAX_VALUE_1 = 7;

    public CalculatePriceHandler() {
    }
    
    public void	abortWorkItem(WorkItem workItem, WorkItemManager manager) {}

    public void	executeWorkItem(WorkItem workItem, WorkItemManager manager) {
        
        Random rand = new Random();
        Integer calculatedPrice = (rand.nextInt(PIN_MAX_VALUE_1) + PIN_MIN_VALUE_1);
        
        Map<String,Object> results = new HashMap<String,Object>();
        results.put("calculatedPrice", calculatedPrice);
        
        manager.completeWorkItem(workItem.getId(), results);
    }

}
