package insanebikesteam.insanebikes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ChargeException extends RuntimeException {

    public ChargeException(String message) {
        super(message);
    }
}