package insanebikesteam.insanebikes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoginException extends RuntimeException {

    public LoginException(String message) {
        super(message);
    }
}