package insanebikesteam.insanebikes;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import org.json.JSONException;
import org.json.JSONObject;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RegistrationCodeHandler implements java.io.Serializable, WorkItemHandler {

    static final long serialVersionUID = 1L;
    
    static final int PIN_MIN_VALUE = 1000;
    static final int PIN_MAX_VALUE = 9999;

    public RegistrationCodeHandler() {
    }
    
    public void	abortWorkItem(WorkItem workItem, WorkItemManager manager) {}

    public void	executeWorkItem(WorkItem workItem, WorkItemManager manager) {
        
        String baseUrl = (String)workItem.getParameter("BaseUrl");
        String userCreationJsonResponse = (String)workItem.getParameter("UserCreationJsonResponse");
        User user = (User) workItem.getParameter("User");
        
        Random rand = new Random();
        String registrationCode = "" + (rand.nextInt(PIN_MAX_VALUE) + PIN_MIN_VALUE);
        Date registrationCodeCreated = new Date();
        
        String userUrl = "";
        
        try {
            JSONObject jsonObj = new JSONObject(userCreationJsonResponse);
            String usedId = jsonObj.getString("name");
            userUrl = baseUrl + "/" + usedId + "/.json";
            
            System.out.println("############## UserUrl: " + userUrl);
            
        } catch (JSONException ex) {
            
            System.out.println("############## Chyba: " + ex.getMessage());
        }
        
        user.setRegistration_code(registrationCode);
        user.setRegistration_code_created(registrationCodeCreated);
        
        Map<String,Object> results = new HashMap<String,Object>();
        results.put("UpdatedUser", user);
        results.put("UserUrl", userUrl);
        results.put("UserEmail", user.getEmail());
        results.put("RegistrationCode", "InsaneBikes registration confirmation code: " + registrationCode);
        
        manager.completeWorkItem(workItem.getId(), results);
    }

}
