package insanebikesteam.insanebikes;

import insanebikesteam.insanebikes.User;
import java.lang.Exception;
import java.lang.IllegalArgumentException;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.Map;
import javax.ws.rs.core.UriBuilder;
import org.apache.commons.io.IOUtils;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UsersStatusHandler implements java.io.Serializable, WorkItemHandler {

    static final long serialVersionUID = 1L;

    public UsersStatusHandler() {
    }
    
    public void	abortWorkItem(WorkItem workItem, WorkItemManager manager) {}

    public void	executeWorkItem(WorkItem workItem, WorkItemManager manager) {
        
        String baseUrl = (String)workItem.getParameter("BaseUrl");
        User userToBeCreated = (User) workItem.getParameter("User");
        
        String url = String.format("%1s?startAt=\"%2s\"&endAt=\"%3s\"&orderBy=\"email\"", 
                                        baseUrl, 
                                        userToBeCreated.getEmail(), 
                                        userToBeCreated.getEmail());
                                        
        String response = "";
        
        try {
            response = IOUtils.toString(new URL(url), (Charset) null);
            
        } catch (Exception e){
            System.out.println("############## Chyba: " + e.getMessage());
        }
        
        if(!response.equals("{}")) {
            throw new UserExistsException("User already exists");
        }
        
        Map<String,Object> results = new HashMap<String,Object>();
        manager.completeWorkItem(workItem.getId(), results);
    }

}