package insanebikesteam.insanebikes;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class UserExistsException extends RuntimeException {

    public UserExistsException(String message) {
        super(message);
    }
}